### ISSUE TITLE
Consider alternative log options

### ISSUE THREAD

**Issue by ElliottKasoar** [stfc/janus-core#102]
typer-config, which will be added in #100, includes options to [dump the merged config](https://maxb2.github.io/typer-config/latest/examples/save_config/), e.g.:

```
architecture: mace_mp
calc_kwargs: !!python/object:janus_core.cli.TyperDict
  value:
    model: small
device: cpu
log_file: !!python/object/apply:pathlib.PosixPath
- singlepoint.log
out_file: !!python/object/apply:pathlib.PosixPath
- NaCl-results.xyz
properties:
- energy
read_kwargs: !!python/object:janus_core.cli.TyperDict
  value:
    index: ':'
struct_path: !!python/object/apply:pathlib.PosixPath
- tests
- data
- benzene-traj.xyz
summary: !!python/object/apply:pathlib.PosixPath
- singlepoint_summary.yml
write_kwargs: null
```

The form of the paths isn't the nicest, but arguably this is a better (and much simpler to implement) summary, while things that require more processing e.g. start/end time, atomic structure details etc. could be added (or are already included) in the Python logging.
