### ISSUE TITLE
invalid model produces no warning

### ISSUE THREAD

**Issue by alinelena** [stfc/janus-core#193]
if one specifies an invalid model (eg  file does not exist) janus gets some default... but no warning is printed to let the user know... model loading failed.

**Comment by ElliottKasoar** [comment]
Do you have an example?

If I run `janus singlepoint --struct tests/data/NaCl.cif --arch mace --calc-kwargs "{'model' : 'example'}"` then the error (from MACE) seems fairly clear: `ValueError: Couldn't find MACE model files: example`

**Comment by alinelena** [comment]
yes was with config

```
device: cuda
fmax: 0.01
arch: mace_mp
steps: 1000
calc-kwargs:
    calc_kwargs:
      dispersion: True
      model: mace_agnesi_medium.model
      ```
