### ISSUE TITLE
Set write_results if write_kwargs are specified for phonons etc.

### ISSUE THREAD

**Issue by ElliottKasoar** [stfc/janus-core#273]
Currently, a config such as

```
minimize: True
minimize-kwargs:
  write-kwargs:
    filename: test.extxyz
```

will not write the results of geometry optimization for phonon calculations, as `write_results` is not set to `True`, but it may be useful to set this automatically if a filename is specified, for example.

This probably applies to MD and EoS calculations too.
