### ISSUE TITLE
nvt-csvr ensemble doesn't support temperature ramp

### ISSUE THREAD

**Issue by k-harris27** [stfc/janus-core#413]
Performing an MD simulation with the nvt-csvr ensemble and a temperature ramp, e.g. config.yml:

```YAML
ensemble: nvt-csvr
struct: NaCl.cif
temp-start: 200
temp-end: 300
temp-step: 20
temp-time: 2
steps: 5
temp: 300
```

Returns
```python
AttributeError: 'Bussi' object has no attribute 'set_temperature'
```
